import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { loadEnvironment, validateBackend, projectRoot } from './project-env.mjs';

const require = createRequire(import.meta.url);
const args = process.argv.slice(2);
const mode = args.includes('--local') ? 'local' : args.includes('--test') ? 'test' : 'cloud';
let failed = false;
const check = (name, ok, detail) => { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}: ${detail}`); if (!ok) failed = true; };
const major = Number(process.versions.node.split('.')[0]);
check('Node', [22, 24].includes(major), `${process.version} (supported: 22 or 24; CI: 22)`);
for (const dependency of ['expo', 'tamagui', '@shopify/react-native-skia', '@supabase/supabase-js']) {
  try { check(dependency, true, require(`${dependency}/package.json`).version); }
  catch { check(dependency, false, 'Run npm ci.'); }
}
check('CanvasKit', existsSync(join(projectRoot, 'public/canvaskit.wasm')), 'Generated by npm ci postinstall.');
try {
  const environment = loadEnvironment(mode);
  check('Backend mode', true, mode === 'local' ? 'isolated SQLite; cloud variables removed' : `${mode} configuration valid; public key accepted`);
  if (args.includes('--backend') && mode !== 'local') {
    const { url, key } = validateBackend(environment, mode);
    const health = await fetch(`${url}/auth/v1/health`, { headers: { apikey: key }, signal: AbortSignal.timeout(10000) });
    check('Supabase health', health.ok, `HTTP ${health.status}`);
    for (const [table, columns] of [['user_settings', 'user_id'], ['intake_log', 'id,consumed_at_utc'], ['tracked_items', 'id'], ['tracker_entries', 'id'], ['tracker_preferences', 'user_id']]) {
      const response = await fetch(`${url}/rest/v1/${table}?select=${columns}&limit=0`, {
        headers: { apikey: key, Authorization: `Bearer ${key}` }, signal: AbortSignal.timeout(10000)
      });
      check(`Schema ${table}`, response.ok, response.ok ? 'available (zero rows requested)' : `HTTP ${response.status}; check public API configuration and apply migrations`);
    }
  }
} catch (error) { check('Backend', false, error.message); }
process.exitCode = failed ? 1 : 0;
