import {test,expect,onboard,waterTarget} from './helpers';
import type{Page}from '@playwright/test';
async function displayUnit(page:Page,tracker:string,unit:string){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Units',exact:true}).click();await page.getByRole('button',{name:tracker,exact:true}).click();await page.getByRole('button',{name:unit,exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();}
test('unit switches preserve source plan quantities through edit save and reload',async({page})=>{
 await onboard(page);await waterTarget(page,'80');await displayUnit(page,'Water','mL');
 await expect(page.getByLabel('Water today:',{exact:false})).toHaveAttribute('aria-label',/^Water today: 0 mL\. \/ 2365\.88 mL\./);
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Targets',exact:true}).click();await page.getByRole('button',{name:'Water',exact:true}).click();
 expect(Number(await page.getByLabel('Optional target · mL',{exact:true}).inputValue())).toBeCloseTo(2365.882365,6);await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();
 await displayUnit(page,'Water','oz');await expect(page.getByLabel('Water today:',{exact:false})).toHaveAttribute('aria-label',/^Water today: 0 oz\. \/ 80 oz\./);await page.reload();await expect(page.getByLabel('Water today:',{exact:false})).toHaveAttribute('aria-label',/^Water today: 0 oz\. \/ 80 oz\./);
 await page.getByRole('button',{name:'Supps',exact:true}).click();await page.getByRole('button',{name:'Add tracker',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Unit conversion fixture');await page.getByLabel('Quantity target (optional)',{exact:true}).fill('5');await page.getByLabel('Quantity limit (optional)',{exact:true}).fill('10');await page.getByRole('button',{name:'Save tracker',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();
 await displayUnit(page,'Unit conversion fixture','mg');await page.getByRole('button',{name:'Supps',exact:true}).click();await page.getByRole('group',{name:'Unit conversion fixture tracker',exact:true}).getByRole('button',{name:'Edit profile',exact:true}).click();
 await expect(page.getByLabel('Quantity target (optional)',{exact:true})).toHaveValue('5000');await expect(page.getByLabel('Quantity limit (optional)',{exact:true})).toHaveValue('10000');await page.getByRole('button',{name:'Save tracker',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();
 await displayUnit(page,'Unit conversion fixture','g');await page.getByRole('button',{name:'Supps',exact:true}).click();await page.reload();await page.getByRole('group',{name:'Unit conversion fixture tracker',exact:true}).getByRole('button',{name:'Edit profile',exact:true}).click();await expect(page.getByLabel('Quantity target (optional)',{exact:true})).toHaveValue('5');await expect(page.getByLabel('Quantity limit (optional)',{exact:true})).toHaveValue('10');await page.getByRole('button',{name:'Cancel',exact:true}).click();
});

