name: Format code
on:
  pull_request:
permissions:
  contents: write
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Format code
        run: |
          cd expo-app
          npx prettier . --write

      - name: Commit and push changes
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git commit -m "Apply Prettier formatting"
            # Push to the PR's SOURCE BRANCH
            git push origin HEAD:${{ github.head_ref }}
          fi