name: autofix.ci
on:
  pull_request:
  push:
permissions:
  contents: write  # Required for autofix to push changes
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies and run Prettier
        run: |
          cd expo-app
          npm ci
          npx prettier . --write

      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
          allow-dotgithub: true  # Allow modifying workflow files